### ISSUE TITLE
cmi bungee portals

### ISSUE THREAD

**Issue by FxBread** [pintux98/CMIV#1]
Hello When I try to set teleport location from one server to another, it doesn't seem to detect the portal destination on the other server.
![image](https://github.com/pintux98/CMIV/assets/57861523/707ab919-99fe-4dd4-ad4b-27203f9fe1d4)

**Comment by pintux98** [comment]
Hi, thank you . I’ll check the issue as soon as I get back home from holiday

**Comment by pintux98** [comment]
> 

Hi, can you please provide more information, like what placeholder do you use, what plugin for the GUI ecc to be able to identify the issue

**Comment by pintux98** [comment]
Closing due inactivity.
