### ISSUE TITLE
[BUG] Slow "pairing"

### ISSUE THREAD

**Issue by saph1s** [pintux98/CMIV#2]
**Describe the bug**
After restarting the server it takes a long time to connect to CMIV (about 5-15 minutes)

**To Reproduce**
1. Install CMIV on Velocity
2. Install CMI on backend servers
3. Check with /cmi version

**Expected behavior**

**Screenshots / Pastebin**
![image](https://github.com/pintux98/CMIV/assets/60987685/e67d9def-9bf0-4ded-b9f3-223d555de8df)
1st version log - survival server, 2nd version log - lobby

**Plugin (please complete the following information):**
 - CMI: [e.g. 9.6.7.1]
 - CMI Lib:  [e.g. 1.4.2.2]

**Additional context**
None

**Comment by pintux98** [comment]
Hi @Saph1s , please contact me on discord > pintux . So i can provide you with a new test version
